from app import app

from models import db, User, Exercise, Workout

if __name__ == '__main__':
    with app.app_context():
        print("Starting seed...")

        #User.query.delete()
        Exercise.query.delete()
        #Workout.query.delete()

        #chest
        e1 = Exercise(name = "Dumbbell Bench Press", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-9e-dumbbell-bench-press-m2-16x9.jpg", description = "Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other. Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width. Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position. Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly.", muscle = "chest")

        e2 = Exercise(name = "Pushups", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-102a-push-up-m2-16x9.jpg", description = "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.", muscle = "chest")

        e3 = Exercise(name = "Dumbbell Flyes", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-31e-dumbbell-chest-fly-m2-16x9.jpg", description = "Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other. Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you're pressing them, but stop and hold just before you lock out. This will be your starting position. With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint. Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights. Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.", muscle = "chest")

        #forearms
        e4 = Exercise(name = "Palms-down Wrist Curl Over Bench", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-62e-palms-down-wrist-curl-over-bench-m1-16x9.jpg", description = "Start out by placing a barbell on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench. Use your arms to grab the barbell with a pronated grip (palms down) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge. Start out by curling your wrist upwards and exhaling. Slowly lower your wrists back down to the starting position while inhaling. Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.", muscle = "forearms")

        e5 = Exercise(name = "Seated One-Arm Dumbbell Palms-Up Wrist Curl", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/386/Male/l/386_1.jpg", description = "Sit on a flat bench with a dumbbell in your right hand. Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart. Lean forward and place your right forearm on top of your upper right thigh with your palm up. Tip: Make sure that the front of the wrist lies on top of your knees. This will be your starting position. Lower the dumbbell as far as possible as you keep a tight grip on the dumbbell. Inhale as you perform this movement. Now curl the dumbbell as high as possible as you contract the forearms and as you exhale. Keep the contraction for a second before you lower again. Tip: The only movement should happen at the wrist. Switch arms and repeat the movement.", muscle = "forearms")

        e6 = Exercise(name = "Dumbbell Farmer's Carry", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-30d-dumbbell-farmers-walk-m5-16x9.jpg", description = "There are various implements that can be used for the farmers walk. These can also be performed with heavy dumbbells or short bars if these implements aren't available. Begin by standing between the implements. After gripping the handles, lift them up by driving through your heels, keeping your back straight and your head up. Walk taking short, quick steps, and don't forget to breathe. Move for a given distance, typically 50-100 feet, as fast as possible.", muscle = "forearms")

        #Lats
        e7 = Exercise(name="Pullups", image="https://www.bodybuilding.com/images/2020/xdb/originals/xdb-92c-pull-up-m2-16x9.jpg", description="Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.", muscle = "lats")

        e8 = Exercise(name="Close-Grip Front Lat Pulldown", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-73c-close-grip-pull-down-m2-16x9.jpg", description = "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar. Grab the bar with the palms facing forward using the prescribed grip. As you have both arms extended in front of you - while holding the bar at the chosen grip width - bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary (only the arms should move). The forearms should do no other work except for holding the bar; therefore do not try to pull the bar down using the forearms. After a second in the contracted position, while squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.", muscle = "lats")

        e9 = Exercise(name="Straight-Arm Rope Pull-Down", image = "https://www.bodybuilding.com/images/2020/xdb/originals/2019-xdb-105c-straight-arm-rope-pull-down-m2.jpg", description ="Attach a rope to a high pulley and make your weight selection. Stand a couple feet back from the pulley with your feet staggered and take the rope with both hands. Lean forward from the hip, keeping your back straight, with your arms extended up in front of you. This will be your starting position. Keeping your arms straight, extend the shoulder to pull the rope down to your thighs. Pause at the bottom of the motion, squeezing your lats. Return to the starting position without allowing the weight to fully rest on the stack.", muscle = "lats")

        #midback
        e10 = Exercise(name="T-Bar Row", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/1931/Male/l/1931_2.jpg", description="Position a bar into a landmine or in a corner to keep it from moving. Load an appropriate weight onto your end. Stand over the bar, and position a Double D row handle around the bar next to the collar. Using your hips and legs, rise to a standing position. Assume a wide stance with your hips back and your chest up. Your arms should be extended. This will be your starting position. Pull the weight to your upper abdomen by retracting the shoulder blades and flexing the elbows. Do not jerk the weight or cheat during the movement. After a brief pause, return to the starting position.", muscle = "midback")

        e11 = Exercise(name= "Reverse-Grip Bent-Over Row", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-02b-reverse-grip-bent-over-row-m2-16x9.jpg", description = "Stand erect while holding a barbell with a supinated grip (palms facing up). Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position. While keeping the torso stationary, lift the barbell as you breathe out, keeping the elbows close to the body and not doing any force with the forearm other than holding the weights. On the top contracted position, squeeze the back muscles and hold for a second. Slowly lower the weight again to the starting position as you inhale.", muscle = "midback")

        e12 = Exercise(name = "One-Arm Dumbbell Row", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-13e-single-arm-bench-dumbbell-row-m2-16x9.jpg", description = "Choose a flat bench and place a dumbbell on each side of it. Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support. Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position. Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms. Lower the resistance straight down to the starting position. Breathe in as you perform this step. Repeat the movement for the specified amount of repetitions. Switch sides and repeat again with the other arm.", muscle = "midback")

        #lowback
        e13 = Exercise(name="Back Extension", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-16m-back-extension-m1-16x9.jpg", description = "Lie face down on a hyperextension bench, tucking your ankles securely under the footpads. Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back. Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.", muscle = "lowback")

        e14 = Exercise(name = "Barbell Deficit Deadlift", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-67e-barbell-deficit-deadlift-m2-16x9.jpg", description = "Begin by having a platform or weight plates that you can stand on, usually 1-3 inches in height. Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an overhand grip or an over/under grip on heavier sets. With your feet, and your grip set, take a big breath and then lower your hips and bend the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar. Lower the bar by bending at the hips and guiding it to the floor.", muscle = "lowback")

        e15 = Exercise(name = "Superman", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-56a-superman-m2-16x9.jpg", description = "To begin, lie straight and face down on the floor or exercise mat. Your arms should be fully extended in front of you. This is the starting position. Simultaneously raise your arms, legs, and chest off of the floor and hold this contraction for 2 seconds. Tip: Squeeze your lower back to get the best results from this exercise. Remember to exhale during this movement. Note: When holding the contracted position, you should look like superman when he is flying. Slowly begin to lower your arms, legs and chest back down to the starting position while inhaling.", muscle = "lowback")

        #quads
        e16 = Exercise(name = "Barbell Squat", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-50b-barbell-back-squat-m2-16x9.jpg", description = "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it. Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso. Step away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times and maintain a straight back. This will be your starting position. Begin to slowly lower the bar by bending the knees and sitting back with your hips as you maintain a straight posture with the head up. Continue down until your hamstrings are on your calves. Inhale as you perform this portion of the movement. Begin to raise the bar as you exhale by pushing the floor with the heel or middle of your foot as you straighten the legs and extend the hips to go back to the starting position.", muscle = "quads")

        e17 = Exercise(name = "Barbell Walking Lunge", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-45b-barbell-walking-lunge-m2-16x9.jpg", description = "Begin standing with your feet shoulder width apart and a barbell across your upper back. Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot. Drive through the heel of your lead foot and extend both knees to raise yourself back up. Step forward with your rear foot, repeating the lunge on the opposite leg.", muscle = "quads")

        e18 = Exercise(name = "Leg Press", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-44m-leg-press-m2-16x9.jpg", description = "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position. As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle. Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale. Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.", muscle = "quads")

        #hamstrings
        e19 = Exercise(name = "Barbell Deadlift", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-07b-barbell-deadlift-m1-16x9.jpg", description = "Approach the bar so that it is centered over your feet. Your feet should be about hip-width apart. Bend at the hip to grip the bar at shoulder-width allowing your shoulder blades to protract. Typically, you would use an alternating grip. With your feet and your grip set, take a big breath and then lower your hips and flex the knees until your shins contact the bar. Look forward with your head. Keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar. Lower the bar by bending at the hips and guiding it to the floor.", muscle = "hamstrings")

        e20 = Exercise(name = "Romanian Deadlift With Dumbbells", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-9d-dumbbell-stiff-legged-deadlift-m2-16x9.jpg", description = "Begin in a standing position with a dumbbell in each hand. Ensure that your back is straight and stays that way for the duration of the exercise. Allow your arms to hang perpendicular to the floor, with the wrists pronated and the elbows pointed to your sides. This will be your starting position. Initiate the movement by flexing your hips, slowly pushing your butt as far back as you can. This should entail a horizontal movement of the hips, rather than a downward movement. The knees should only partially bend, and your weight should remain on your heels Drive your butt back as far as you can, which should generate tension in your hamstrings as your hands approach knee level. Maintain an arch in your back throughout the exercise. When your hips cannot perform any further backward movement, pause, and then slowly return to the starting position by extending the hips.", muscle = "hamstrings")

        e21 = Exercise(name = "Lying Leg Curls", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-20m-lying-leg-curl-m2-16x9.jpg", description = "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment. Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position. As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second. As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions.", muscle = "hamstrings")

        #calves
        e22 = Exercise(name = "Standing Calf Raises", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-117s-standing-calf-raise-m2-16x9.jpg", description = "Adjust the padded lever of the calf raise machine to fit your height. Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. This will be your starting position. Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down. Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.", muscle = "calves")

        e23 = Exercise(name = "Seated Calf Raises", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-13m-machine-seated-calf-raise-m2-16x9.jpg", description = "Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter. Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward. Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position. Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement. Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second.", muscle = "calves")

        e24 = Exercise(name = "Calf Press On The Leg Press Machine", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-49m-leg-press-calf-raise-m2-16x9.jpg", description = "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you without locking your knees. Your torso and the legs should make perfect 90-degree angle. Now carefully place your toes and balls of your feet on the lower portion of the platform with the heels extending off. This will be your starting position. Press on the platform by raising your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down. Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.", muscle = "calves")

        #triceps
        e25 = Exercise(name = "Triceps Dip", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-1m-triceps-dip-m2-16x9.jpg", description = "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars. Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm. Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.", muscle = "triceps")

        e26 = Exercise(name = "EZ-Bar Skullcrusher", image ="https://www.bodybuilding.com/images/2020/xdb/originals/xdb-94s-ez-bar-skullcrusher-m2-16x9.jpg", description = "Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position. Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead. Lift the bar back to the starting position by extending the elbow and exhaling.", muscle = "triceps")

        e27 = Exercise(name = "Triceps Pushdown - Rope Attachment", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-16c-cable-rope-push-down-m2-16x9.jpg", description = "Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other). Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the rope with the palms facing each other. This is your starting position. Using the triceps, bring the rope down as you bring each side of the rope to the side of your thighs. At the end of the movement the arms are fully extended and perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement. After holding for a second, at the contracted position, bring the rope slowly up to the starting point. Breathe in as you perform this step.", muscle = "triceps")

        #traps
        e28 = Exercise(name = "Smith Machine Shrug", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-alt-14t-smith-machine-shrug-m2-16x9.jpg", description = "To begin, set the bar height on the smith machine around the middle of your thighs. Once the correct height is chosen and the bar is loaded, grab the bar using a pronated grip (palms facing you) shoulder width apart from each other. Lift the barbell up and fully extend your arms with your back straight. This is the starting position. While exhaling, elevate the bar by raising your shoulders until they come close to touching your ears. Hold the contraction for a second before lowering the bar back down to the starting position while inhaling.", muscle = "traps")

        e29 = Exercise(name= "Standing Dumbbell Shrug", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-115d-standing-dumbbell-shrug-m2-16x9.jpg", description = "Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides. Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down. Lower the dumbbells back to the original position.", muscle = "traps")

        e30 = Exercise(name= "Smith Machine Upright Row", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-22t-smith-machine-upright-row-m2-16x9.jpg", description = "To begin, set the bar on the smith machine to a height that is around the middle of your thighs. Once the correct height is chosen and the bar is loaded, grasp the bar using a pronated (palms forward) grip that is shoulder width apart. You may need some wrist wraps if using a significant amount of weight. Lift the barbell up and fully extend your arms with your back straight. There should be a slight bend at the elbows. This is the starting position. Use your side shoulders to lift the bar as you exhale. The bar should be close to the body as you move it up. Continue to lift it until it nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the bar, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement. Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.", muscle = "traps")

        #shoulders
        e31 = Exercise(name="Seated Dumbbell Press", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-50e-seated-dumbbell-shoulder-press-m2-16x9.jpg", description = "Grab a couple of dumbbells and sit on a military press bench or a utility bench that has a back support on it as you place the dumbbells upright on top of your thighs. Clean the dumbbells up one at a time by using your thighs to bring the dumbbells up to shoulder height at each side. Rotate the wrists so that the palms of your hands are facing forward. This is your starting position. As you exhale, push the dumbbells up until they touch at the top. After a second pause, slowly come down back to the starting position as you inhale.", muscle = "shoulders")

        e32 = Exercise(name="Lateral Raise", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/270/Male/l/270_2.jpg", description = "Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso. The palms of the hands should be facing your torso. Your feet should be about shoulder width apart. This will be your starting position. Keeping your arms straight and the torso stationary, lift the weights out to your sides until they are about shoulder level height while exhaling. Feel the contraction for a second and begin to lower the weights back down to the starting position while inhaling. Tip: Keep the palms facing down with the little finger slightly higher while lifting and lowering the weights as it will concentrate the stress on your shoulders mainly.", muscle = "shoulders")

        e33 = Exercise(name = "Incline Dumbbell Reverse Fly", image = "https://www.bodybuilding.com/images/2020/xdb/originals/2020-xdb-13n-incline-dumbbell-reverse-fly-m2.jpg", description = "To begin, lie down on an incline bench with the chest and stomach pressing against the incline. Have the dumbbells in each hand with the palms facing each other (neutral grip). Extend the arms in front of you so that they are perpendicular to the angle of the bench. The legs should be stationary while applying pressure with the ball of your toes. This is the starting position. Maintaining the slight bend of the elbows, move the weights out and away from each other (to the side) in an arc motion while exhaling. Tip: Try to squeeze your shoulder blades together to get the best results from this exercise. The arms should be elevated until they are parallel to the floor. Feel the contraction and slowly lower the weights back down to the starting position while inhaling.", muscle = "shoulders")

        #abs
        e34 = Exercise(name = "Hanging Toes-To-Bar", image = "https://www.bodybuilding.com/images/2020/xdb/originals/2019-xdb-128c-hanging-toes-to-bar-m2.jpg", description = "Hang from a chin-up bar with your legs and feet together using an overhand grip (palms facing away from you) that is slightly wider than shoulder width. Tip: You may use wrist wraps in order to facilitate holding on to the bar. Now bend your knees at a 90 degree angle and bring the upper legs forward so that the calves are perpendicular to the floor while the thighs remain parallel to it. This will be your starting position. Pull your legs up as you exhale until you almost touch your shins with the bar above you. Tip: Try to straighten your legs as much as possible while at the top. Lower your legs as slowly as possible until you reach the starting position. Tip: Avoid swinging and using momentum at all times.", muscle = "abs")

        e35 = Exercise(name = "Ab Roller", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-2s-ab-wheel-roll-out-m2-16x9.jpg", description = "Hold the Ab Roller with both hands and kneel on the floor. Now place the ab roller on the floor in front of you so that you are on all your hands and knees (as in a kneeling push up position). This will be your starting position. Slowly roll the ab roller straight forward, stretching your body into a straight position. Tip: Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement. After a pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Tip: Go slowly and keep your abs tight at all times.", muscle = "abs")

        e36 = Exercise(name = "Cross-Body Crunch", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-176a-elbow-to-knee-crunch-m2-16x9.jpg", description = "Lie flat on your back and bend your knees about 60 degrees. Keep your feet flat on the floor and place your hands loosely behind your head. This will be your starting position. Now curl up and bring your right elbow and shoulder across your body while bring your left knee in toward your left shoulder at the same time. Reach with your elbow and try to touch your knee. Exhale as you perform this movement. Tip: Try to bring your shoulder up towards your knee rather than just your elbow and remember that the key is to contract the abs as you perform the movement; not just to move the elbow. Now go back down to the starting position as you inhale and repeat with the left elbow and the right knee.", muscle = "abs")

        #glutes
        e37 = Exercise(name = "Barbell Hip Thrust", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-24e-barbell-hip-thrust-m2-16x9.jpg", description = "Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise. Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it. Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position.", muscle = "glutes")

        e38 = Exercise(name="Single-Leg Glute Bridge", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-61a-single-leg-glute-bridge-m3-16x9.jpg", description = "Lay on the floor with your feet flat and knees bent. Raise one leg off of the ground, pulling the knee to your chest. This will be your starting position. Execute the movement by driving through the heel, extending your hip upward and raising your glutes off of the ground. Extend as far as possible, pause and then return to the starting position.", muscle = "glutes")

        e39 = Exercise(name = "Step-Up With Knee Raise", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-70e-step-up-with-knee-raise-m2-16x9.jpg", description = "Stand facing a box or bench of an appropriate height with your feet together. This will be your starting position. Begin the movement by stepping up, putting your left foot on the top of the bench. Extend through the hip and knee of your front leg to stand up on the box. As you stand on the box with your left leg, flex your right knee and hip, bringing your knee as high as you can. Reverse this motion to step down off the box, and then repeat the sequence on the opposite leg.", muscle = "glutes")

        #biceps
        e40 = Exercise(name = "Incline Hammer Curls", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/882/Male/l/882_2.jpg", description = "Seat yourself on an incline bench with a dumbbell in each hand. You should pressed firmly against he back with your feet together. Allow the dumbbells to hang straight down at your side, holding them with a neutral grip. This will be your starting position. Initiate the movement by flexing at the elbow, attempting to keep the upper arm stationary. Continue to the top of the movement and pause, then slowly return to the start position.", muscle = "biceps")

        e41 = Exercise(name = "Wide-Grip Barbell Curl", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-22b-wide-grip-barbell-curl-m2-16x9.jpg", description = "Stand up with your torso upright while holding a barbell at the wide outer handle. The palm of your hands should be facing forward. The elbows should be close to the torso. This will be your starting position. While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard. Slowly begin to bring the bar back to starting position as your breathe in.", muscle = "biceps")

        e42 = Exercise(name = "Dumbbell Bicep Curl", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-2d-dumbbell-biceps-curl-m2-16x9.jpg", description = "Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position. Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Then, inhale and slowly begin to lower the dumbbells back to the starting position.", muscle = "biceps")

        #adductors
        e43 = Exercise(name = "Thigh Adductor", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-74m-thigh-adductor-m1-16x9.jpg", description = "To begin, sit down on the adductor machine and select a weight you are comfortable with. When your legs are positioned properly on the leg pads of the machine, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position. Slowly press against the machine with your legs to move them towards each other while exhaling. Feel the contraction for a second and begin to move your legs back to the starting position while breathing in.", muscle = "adductors")

        e44 = Exercise(name = "Band Hip Adductions", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/850/Male/l/850_1.jpg", description = "Anchor a band around a solid post or other object. Stand with your left side to the post, and put your right foot through the band, getting it around the ankle. Stand up straight and hold onto the post if needed. This will be your starting position. Keeping the knee straight, raise your right legs out to the side as far as you can. Return to the starting position and repeat for the desired rep count. Switch sides.", muscle = "adductors")

        e45 = Exercise(name = "Groiners", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/592/Male/l/592_2.jpg", description = "Begin in a pushup position on the floor. This will be your starting position. Using both legs, jump forward landing with your feet next to your hands. Keep your head up as you do so. Return to the starting position and immediately repeat the movement, continuing for 10-20 repetitions.", muscle = "adductors")

        #abductors
        e46 = Exercise(name = "Prone Hip Circles", image = "https://www.bodybuilding.com/images/2020/may/874_3l.jpg", description = "Position yourself on your hands and knees on the ground. Maintaining good posture, raise one bent knee off of the ground. This will be your starting position. Keeping the knee in a bent position, rotate the femur in an arc, attempting to make a big circle with your knee. Perform this slowly for a number of repetitions, and repeat on the other side.", muscle = "abductors")

        e47 = Exercise(name = "Thigh Abductor", image = "https://www.bodybuilding.com/images/2020/xdb/originals/xdb-73m-thigh-abductor-m2-16x9.jpg", description = "To begin, sit down on the abductor machine and select a weight you are comfortable with. When your legs are positioned properly, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position. Slowly press against the machine with your legs to move them away from each other while exhaling. Feel the contraction for a second and begin to move your legs back to the starting position while breathing in.", muscle = "abductors")

        e48 = Exercise(name = "Standing Hip Circles", image = "https://www.bodybuilding.com/exercises/exerciseImages/sequences/873/Male/l/873_2.jpg", description = "Begin standing on one leg, holding to a vertical support. Raise the unsupported knee to 90 degrees. This will be your starting position. Open the hip as far as possible, attempting to make a big circle with your knee. Perform this movement slowly for a number of repetitions, and repeat on the other side.", muscle = "abductors")

        exercises = [e1, e2, e3, e4, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35, e36, e37, e38, e39, e40, e41, e42, e43, e44, e45, e46, e47, e48]

        db.session.add_all(exercises)
        db.session.commit()